export const primaryColor = '#2D033B';
export const secondaryColor = '#810CA8';
export const tertiaryColor = '#C147E9';
export const accentColor='#E5B8F4';
export const darkGrey='#604B67';
export const lightGrey = '#E4DDE6';
export const trueGrey = '#F9F9F9'
export const black = '#333333';
export const backgroundWhite='';
export const backgroundPink='#F3EDF7';
export const trueWhite = '#FFFFFF';
export const publishedGreen = '#9AE6B4';
export const draftRed = '#FC8181';
export const scheduledYellow = '#FBD38D';
export const transparent = '#00000000'